### ISSUE TITLE
Error when deploying a building from the CLI (windows)

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#820]
Tried in Powershell and CMD . CLI command was:
> ds apply -n "devnet" -R -f .

Before signing:
> cog query error: CombinedError: [Network] undefined
    at makeErrorResult (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:124823:10)
    at Object.error (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:125247:35)
    at Object.25234d40-752f-483a-84df-08ea0fb9e9e7 (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:145668:24)
    at emit (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:145423:87)
    at Object.emit (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:145448:11)
    at socket2.onmessage (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:145534:19)
    at callListener (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:75930:18)
    at WebSocket4.onMessage (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:75865:13)
    at WebSocket4.emit (node:events:513:28)
    at Receiver2.receiverOnMessage (C:\Users\speed\AppData\Roaming\npm\node_modules\@playmint\ds-cli\dist\ds.js:76918:24) {
  graphQLErrors: [],
  networkError: [
    {
      message: 'Cannot query field "logs" on type "BlockEvent". Did you mean "sigs"?',

After signing:

> file: basic-factory.yaml
error:Error: Field "dispatch" argument "nonce" of type "Int!" is required, but it was not provided.
actions:[{"name":"REGISTER_ITEM_KIND","args":["0x6a7a67f0d736dc9200000000000000020000000200000002","VIP Rocket 2","30-115"]}]

**Comment by chrisfarms** [comment]
Looks like you are using an old version of `ds` cli.... you'll need to install it again to get the latest one.

**Comment by PlaymintPaul** [comment]
That worked!
